<template><h2 id="while-循环介绍" tabindex="-1"><a class="header-anchor" href="#while-循环介绍" aria-hidden="true">#</a> while 循环介绍</h2>
<p>while 在 shell 中也是负责循环的语句，和 for 一样。因为功能一样，很多人在学习和工作中的脚本遇到循环，到底该使用 for 还是 while 呢？很多人不知道，就造就了有人一遇到循环就是 for 或者一味的 while。我觉得可以按照循环次数的情况来使用，如果已经知道循环次数，那么就建议使用 for，比如说一天需要循环 24 次；如果不知道要循环多少次，那么就使用 while，比如我们作业中要求写的猜数字，每个人猜对一个数字的次数都是不能固定的，也就是未知的。所以这样的循环我就建议大家用 while 了。</p>
<h2 id="while-循环语法" tabindex="-1"><a class="header-anchor" href="#while-循环语法" aria-hidden="true">#</a> while 循环语法</h2>
<p>语法格式</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token keyword">while</span> <span class="token punctuation">[</span> condition <span class="token punctuation">]</span><span class="token punctuation">;</span><span class="token keyword">do</span>
	commands
<span class="token keyword">done</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><blockquote>
<p>注意：条件为真，while 才会循环；条件为假，while 停止循环</p>
<p>条件可以是之前学习的五种运算：数学比较、字符串比较、文件类型、逻辑运算、赋值运算</p>
</blockquote>
<p>小作业试写
while 循环输出 1-9，当输出到5的时候，停止循环。（break）
while 循环输出 1-9，当输出5的时候，跳过本次循环。（continue）
while 循环输出 1-9，每隔 1 秒输出一个数字。（sleep）
while 循环嵌套 for 循环，或者 for 循环嵌套while循环（九九乘法表）
while 循环输出 1-10 嵌套 if 判断（奇偶数判断）</p>
<p>补充：如果把某一段代码注释，不用每一行前面都加上#，可以利用定义函数方法来注释</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function-name function">name</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
	commands
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>运行脚本，上面花括号{ }内的代码将不会执行。</p>
<h2 id="while-实战" tabindex="-1"><a class="header-anchor" href="#while-实战" aria-hidden="true">#</a> while 实战</h2>
<p>使用 while 遍历文件内容（<code>grep</code> 过滤）</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span>root@localhost ~ <span class="token punctuation">]</span><span class="token comment"># vim while_read.sh</span>
<span class="token comment">#!/bin/bash</span>
<span class="token function">cat</span> /etc/passwd <span class="token operator">|</span> <span class="token function">grep</span> <span class="token string">"bash"</span> <span class="token operator">|</span> <span class="token keyword">while</span> <span class="token builtin class-name">read</span> i<span class="token punctuation">;</span><span class="token keyword">do</span>
	<span class="token builtin class-name">echo</span> <span class="token variable">$i</span>
<span class="token keyword">done</span> 
<span class="token punctuation">[</span>root@localhost ~ <span class="token punctuation">]</span><span class="token comment"># bash while_read.sh</span>
root:x:0:0:root:/root:/bin/bash
karin:x:1000:1000:karin,,,:/home/karin:/bin/bash
<span class="token punctuation">[</span>root@localhost ~ <span class="token punctuation">]</span><span class="token comment"># </span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>九九乘法表（嵌套）</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token punctuation">[</span>root@localhost ~ <span class="token punctuation">]</span><span class="token comment"># vim 99.sh</span>
<span class="token comment">#!/bin/bash</span>
<span class="token assign-left variable">n</span><span class="token operator">=</span><span class="token number">1</span>
<span class="token keyword">while</span> <span class="token punctuation">[</span> <span class="token variable">$n</span> -lt <span class="token number">10</span> <span class="token punctuation">]</span><span class="token punctuation">;</span><span class="token keyword">do</span>
        <span class="token keyword">for</span> <span class="token variable"><span class="token punctuation">((</span>m<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">;</span>m<span class="token operator">&lt;=</span>$n<span class="token punctuation">;</span>m<span class="token operator">++</span><span class="token punctuation">))</span></span><span class="token punctuation">;</span><span class="token keyword">do</span>
                <span class="token builtin class-name">echo</span> -n -e  <span class="token string">"<span class="token variable">$m</span>*<span class="token variable">$n</span>=<span class="token variable"><span class="token variable">$((</span>n<span class="token operator">*</span>m<span class="token variable">))</span></span><span class="token entity" title="\t">\t</span>"</span>
        <span class="token keyword">done</span>
        <span class="token builtin class-name">echo</span>
        <span class="token assign-left variable">n</span><span class="token operator">=</span><span class="token variable"><span class="token variable">$((</span>n<span class="token operator">+</span><span class="token number">1</span><span class="token variable">))</span></span>
<span class="token keyword">done</span>
<span class="token punctuation">[</span>root@linux ~ <span class="token punctuation">]</span><span class="token comment"># bash 99.sh</span>
<span class="token number">1</span>*1<span class="token operator">=</span><span class="token number">1</span>	
<span class="token number">1</span>*2<span class="token operator">=</span><span class="token number">2</span>	<span class="token number">2</span>*2<span class="token operator">=</span><span class="token number">4</span>	
<span class="token number">1</span>*3<span class="token operator">=</span><span class="token number">3</span>	<span class="token number">2</span>*3<span class="token operator">=</span><span class="token number">6</span>	<span class="token number">3</span>*3<span class="token operator">=</span><span class="token number">9</span>	
<span class="token number">1</span>*4<span class="token operator">=</span><span class="token number">4</span>	<span class="token number">2</span>*4<span class="token operator">=</span><span class="token number">8</span>	<span class="token number">3</span>*4<span class="token operator">=</span><span class="token number">12</span>	<span class="token number">4</span>*4<span class="token operator">=</span><span class="token number">16</span>	
<span class="token number">1</span>*5<span class="token operator">=</span><span class="token number">5</span>	<span class="token number">2</span>*5<span class="token operator">=</span><span class="token number">10</span>	<span class="token number">3</span>*5<span class="token operator">=</span><span class="token number">15</span>	<span class="token number">4</span>*5<span class="token operator">=</span><span class="token number">20</span>	<span class="token number">5</span>*5<span class="token operator">=</span><span class="token number">25</span>	
<span class="token number">1</span>*6<span class="token operator">=</span><span class="token number">6</span>	<span class="token number">2</span>*6<span class="token operator">=</span><span class="token number">12</span>	<span class="token number">3</span>*6<span class="token operator">=</span><span class="token number">18</span>	<span class="token number">4</span>*6<span class="token operator">=</span><span class="token number">24</span>	<span class="token number">5</span>*6<span class="token operator">=</span><span class="token number">30</span>	<span class="token number">6</span>*6<span class="token operator">=</span><span class="token number">36</span>	
<span class="token number">1</span>*7<span class="token operator">=</span><span class="token number">7</span>	<span class="token number">2</span>*7<span class="token operator">=</span><span class="token number">14</span>	<span class="token number">3</span>*7<span class="token operator">=</span><span class="token number">21</span>	<span class="token number">4</span>*7<span class="token operator">=</span><span class="token number">28</span>	<span class="token number">5</span>*7<span class="token operator">=</span><span class="token number">35</span>	<span class="token number">6</span>*7<span class="token operator">=</span><span class="token number">42</span>	<span class="token number">7</span>*7<span class="token operator">=</span><span class="token number">4</span>
<span class="token number">1</span>*8<span class="token operator">=</span><span class="token number">8</span>	<span class="token number">2</span>*8<span class="token operator">=</span><span class="token number">16</span>	<span class="token number">3</span>*8<span class="token operator">=</span><span class="token number">24</span>	<span class="token number">4</span>*8<span class="token operator">=</span><span class="token number">32</span>	<span class="token number">5</span>*8<span class="token operator">=</span><span class="token number">40</span>	<span class="token number">6</span>*8<span class="token operator">=</span><span class="token number">48</span>	<span class="token number">7</span>*8<span class="token operator">=</span><span class="token number">56</span>	<span class="token number">8</span>*8<span class="token operator">=</span><span class="token number">64</span>	
<span class="token number">1</span>*9<span class="token operator">=</span><span class="token number">9</span>	<span class="token number">2</span>*9<span class="token operator">=</span><span class="token number">18</span>	<span class="token number">3</span>*9<span class="token operator">=</span><span class="token number">27</span>	<span class="token number">4</span>*9<span class="token operator">=</span><span class="token number">36</span>	<span class="token number">5</span>*9<span class="token operator">=</span><span class="token number">45</span>	<span class="token number">6</span>*9<span class="token operator">=</span><span class="token number">54</span>	<span class="token number">7</span>*9<span class="token operator">=</span><span class="token number">63</span>	<span class="token number">8</span>*9<span class="token operator">=</span><span class="token number">72</span>	<span class="token number">9</span>*9<span class="token operator">=</span><span class="token number">81</span>
<span class="token punctuation">[</span>root@localhost ~ <span class="token punctuation">]</span><span class="token comment"># </span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br></div></div></template>
